[tool.poetry]
name = "pslipstream"
version = "0.4.0"
description = "The most informative Home-media backup solution."
license = "GPLv3"
authors = ["PHOENiX <rlaphoenix@pm.me>"]
maintainers = ["PHOENiX <rlaphoenix@pm.me>"]
readme = "README.md"
homepage = "https://github.com/rlaphoenix/pydvdcss"
repository = "https://github.com/rlaphoenix/pydvdcss"
documentation = "https://github.com/rlaphoenix/pydvdcss"
keywords = ["dvd", "wrapper", "library", "videolan", "libdvdcss"]
classifiers = [
    # python ver and license set by poetry automatically
    "Development Status :: 3 - Alpha",
    "Intended Audience :: End Users/Desktop",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Multimedia",
    "Topic :: Multimedia :: Video",
    "Topic :: Multimedia :: Video :: Conversion",
]
include = ["LICENSE", "README.md", "HISTORY.md", "static/*"]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
pycdlib = { git = "https://github.com/clalancette/pycdlib.git", branch = "master" }
pydvdcss = "^1.3.2"
pydvdid-m = "^1.1.1"
appdirs = "^1.4.4"
tqdm = "^4.46.1"
PyYAML = "^5.4.1"
pywin32 = {version = "301", platform = "win32"}
WMI = {version = "^1.5.1", platform = "win32"}
PySide2 = "^5.15.2.1"
coloredlogs = {version = "^15.0", optional = true}

[tool.poetry.dev-dependencies]
pyinstaller = "^4.2"

[tool.poetry.scripts]
slipstream = 'pslipstream.slipstream:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
