[tool.poetry]
name = "pslipstream"
version = "0.1.0"
description = "The most informative Home-media backup solution."
authors = ["PHOENiX <rlaphoenix@pm.me>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = ">=3.6,<3.10"
pycdlib = { git = "https://github.com/rlaphoenix/pycdlib.git", branch = "win32-test" }
pydvdcss = "^1.3.0"
rlapydvdid = "^1.2"
appdirs = "^1.4.4"
tqdm = "^4.46.1"
PyYAML = "^5.4.1"
pywin32 = {version = "228", platform = "win32"}
WMI = {version = "^1.5.1", platform = "win32"}
PySide6 = "^6.0.3"

[tool.poetry.dev-dependencies]
pyinstaller = "^4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
