[tool.poetry]
name = "pslipstream"
version = "0.1.0"
description = "The most informative Home-media backup solution."
authors = ["PHOENiX <rlaphoenix@pm.me>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = ">=3.6,<3.10"
cefpython3 = [
    {version = "66.0", markers = "sys_platform != 'win32'"},
    {version = "66.1", markers = "sys_platform == 'win32'"},
]
pycdlib = "^1.11.0"
pydvdcss = "^1.0.7.post0"
rlapydvdid = "^1.2"
appdirs = "^1.4.4"
tqdm = "^4.46.1"
PyYAML = "^5.4.1"
pywin32 = {version = "228", platform = "win32"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
